export var Configuracion={
  about: "Nacida en Barcelona y ciudadana de allá donde me sienta amada; como buena Sagitario con ascendente en Virgo, amo viajar, cuidar, hacer volar mi imaginación y ser un “culillo inquieto”. La pequeña de dos hijas, nacidas en una familia trabajadora, llena de amor y educada en una valores fuertes sobre la superación en la vida, el perdón y la conciencia tranquila.",
  educadora: " Educadora infantil y social de formación, madre de dos pequeños peludos a los que amo (Stich y Mishka), amante del mar y de lo que soy cuando estoy cerca de él.",
  tengo: 'Tengo momentos de alegría, de tristeza, de añoranza, de miedo, de locura, de éxtasis y así un largo etc..., llevo tiempo trabajando el aprender a vivirlos, a amar mi caos, a amar mis luces y mis sombras,a aceptarme como soy y modificando aquello que no me aporta paz. Estoy aprendiendo a sentirlos, a abrazarme cuando así lo necesito, a acompañarme y a pedir ayuda cuando no soy capaz por mi misma, estoy en el camino y sigo aprendiendo cada día de la mano de las personas que siento que me ofrecen llegar a donde yo quiero estar.',

  aromaterapia: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi corporis eos corrupti, perspiciatis magnam consectetur minus dolorum praesentium culpa sunt quo dolor at quos aliquam tempore suscipit voluptatum temporibus nulla eaque nobis nesciunt quidem numquam? Fugiat optio praesentium laboriosam nulla, sint modi vero porro deserunt reiciendis illo expedita in ipsam soluta omnis eius accusantium ab totam. Natus molestiae, dicta fuga, ratione consequatur vel corporis nam distinctio obcaecati temporibus quasi nemo deserunt nostrum accusamus corrupti? At, repudiandae? Rerum accusantium est dolore ducimus accusamus culpa iure commodi velit ea, nemo laborum impedit architecto, praesentium earum unde quae? Velit cumque, quae minima quos mollitia laboriosam placeat eveniet aut molestias. Incidunt reiciendis tempore numquam totam voluptatem eveniet alias ducimus quo nisi ab iusto pariatur mollitia error, voluptatibus velit explicabo delectus distinctio labore quam iure iste quas! Omnis accusamus ex, quidem consequatur rerum dicta enim odit adipisci magni accusantium possimus fuga fugiat, quasi ullam dolor. Explicabo vel quos excepturi dolores amet aperiam, asperiores ad expedita magnam, aliquid accusantium delectus unde soluta, veniam iure dolore nobis aut illo porro labore ipsa quisquam adipisci quod. Alias officia molestias magni quam fugiat facilis quibusdam sequi laboriosam praesentium facere error, commodi sed odio eveniet! Ducimus temporibus tempore ut ipsam!',

  reflexionesOne: 'Este proyecto nace de poderle dar forma a un modo de vida, de poder hacer llegar al mundo mis pensamientos, mis descubrimientos, pruebas, aciertos, fallos, luchas, anhelos y pasiones.',
  reflexionesTwo: 'En esta web podrás encontrar mucha información así que puedes mirarla con calma y a tu ritmo, y preguntarme sobre cualquier duda que tengas.',
  reflexionesThree: 'Desde hace ya algún tiempo se ha demostrado que el trabajo y la evolución personal desde la visión holística es la más completa, englobando todo el ser, en sus cuatro elementos (cuerpo físico, emocional, intelectual y espiritual).',
  reflexionesFour: 'Mi herramienta principal para éste trabajo es a través de la Aromaterapia y por eso aquí encontrarás como poder beneficiarte de ella, el acompañamiento que necesites para poderla usar y mucha información para ayudarte.',
  reflexionesFive: 'Pero no sólo para ti, sino para toda la familia, sea humana o animal, la naturaleza nos regala miles de gotas de su pureza para poder vivir de una manera más consciente y sin química de laboratorio.',
  reflexionesSix: '¿Que qué más podrás encontrar en esta web? Pues todo aquello que me ha servido a mi y que se me pase por la cabeza que te pueda ayudar desde esa mirada holística, y cómo algunos ejemplos serán lecturas, personas interesantes a conocer, información de piedras preciosas, astrología, sobre sexualidad (la gran olvidada en general pero sobretodo para las mujeres), sobre feminismo, poesía, alimentación de perrxs...',
  reflexionesSeven: 'Pero si quieres conocer mi día a día, te invito a que te des una vuelta por instagram @la_huella_de_mi_vida para verme más en acción!!',


  sexualidad: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi corporis eos corrupti, perspiciatis magnam consectetur minus dolorum praesentium culpa sunt quo dolor at quos aliquam tempore suscipit voluptatum temporibus nulla eaque nobis nesciunt quidem numquam? Fugiat optio praesentium laboriosam nulla, sint modi vero porro deserunt reiciendis illo expedita in ipsam soluta omnis eius accusantium ab totam. Natus molestiae, dicta fuga, ratione consequatur vel corporis nam distinctio obcaecati temporibus quasi nemo deserunt nostrum accusamus corrupti? At, repudiandae? Rerum accusantium est dolore ducimus accusamus culpa iure commodi velit ea, nemo laborum impedit architecto, praesentium earum unde quae? Velit cumque, quae minima quos mollitia laboriosam placeat eveniet aut molestias. Incidunt reiciendis tempore numquam totam voluptatem eveniet alias ducimus quo nisi ab iusto pariatur mollitia error, voluptatibus velit explicabo delectus distinctio labore quam iure iste quas! Omnis accusamus ex, quidem consequatur rerum dicta enim odit adipisci magni accusantium possimus fuga fugiat, quasi ullam dolor. Explicabo vel quos excepturi dolores amet aperiam, asperiores ad expedita magnam, aliquid accusantium delectus unde soluta, veniam iure dolore nobis aut illo porro labore ipsa quisquam adipisci quod. Alias officia molestias magni quam fugiat facilis quibusdam sequi laboriosam praesentium facere error, commodi sed odio eveniet! Ducimus temporibus tempore ut ipsam!',
  oilText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi corporis eos corrupti, perspiciatis magnam consectetur minus dolorum praesentium culpa sunt quo dolor at quos aliquam tempore suscipit voluptatum temporibus nulla eaque nobis nesciunt quidem numquam? Fugiat optio praesentium laboriosam nulla, sint modi vero porro deserunt reiciendis illo expedita in ipsam soluta omnis eius accusantium ab totam. Natus molestiae, dicta fuga, ratione consequatur vel corporis nam distinctio obcaecati temporibus quasi nemo deserunt nostrum accusamus corrupti? At, repudiandae? Rerum accusantium est dolore ducimus accusamus culpa iure commodi velit ea, nemo laborum impedit architecto, praesentium earum unde quae? Velit cumque, quae minima quos mollitia laboriosam placeat eveniet aut molestias. Incidunt reiciendis tempore numquam totam voluptatem eveniet alias ducimus quo nisi ab iusto pariatur mollitia error, voluptatibus velit explicabo delectus distinctio labore quam iure iste quas! Omnis accusamus ex, quidem consequatur rerum dicta enim odit adipisci magni accusantium possimus fuga fugiat, quasi ullam dolor. Explicabo vel quos excepturi dolores amet aperiam, asperiores ad expedita magnam, aliquid accusantium delectus unde soluta, veniam iure dolore nobis aut illo porro labore ipsa quisquam adipisci quod. Alias officia molestias magni quam fugiat facilis quibusdam sequi laboriosam praesentium facere error, commodi sed odio eveniet! Ducimus temporibus tempore ut ipsam!',
  diffuserText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi corporis eos corrupti, perspiciatis magnam consectetur minus dolorum praesentium culpa sunt quo dolor at quos aliquam tempore suscipit voluptatum temporibus nulla eaque nobis nesciunt quidem numquam? Fugiat optio praesentium laboriosam nulla, sint modi vero porro deserunt reiciendis illo expedita in ipsam soluta omnis eius accusantium ab totam. Natus molestiae, dicta fuga, ratione consequatur vel corporis nam distinctio obcaecati temporibus quasi nemo deserunt nostrum accusamus corrupti? At, repudiandae? Rerum accusantium est dolore ducimus accusamus culpa iure commodi velit ea, nemo laborum impedit architecto, praesentium earum unde quae? Velit cumque, quae minima quos mollitia laboriosam placeat eveniet aut molestias. Incidunt reiciendis tempore numquam totam voluptatem eveniet alias ducimus quo nisi ab iusto pariatur mollitia error, voluptatibus velit explicabo delectus distinctio labore quam iure iste quas! Omnis accusamus ex, quidem consequatur rerum dicta enim odit adipisci magni accusantium possimus fuga fugiat, quasi ullam dolor. Explicabo vel quos excepturi dolores amet aperiam, asperiores ad expedita magnam, aliquid accusantium delectus unde soluta, veniam iure dolore nobis aut illo porro labore ipsa quisquam adipisci quod. Alias officia molestias magni quam fugiat facilis quibusdam sequi laboriosam praesentium facere error, commodi sed odio eveniet! Ducimus temporibus tempore ut ipsam!',
  kitText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi corporis eos corrupti, perspiciatis magnam consectetur minus dolorum praesentium culpa sunt quo dolor at quos aliquam tempore suscipit voluptatum temporibus nulla eaque nobis nesciunt quidem numquam? Fugiat optio praesentium laboriosam nulla, sint modi vero porro deserunt reiciendis illo expedita in ipsam soluta omnis eius accusantium ab totam. Natus molestiae, dicta fuga, ratione consequatur vel corporis nam distinctio obcaecati temporibus quasi nemo deserunt nostrum accusamus corrupti? At, repudiandae? Rerum accusantium est dolore ducimus accusamus culpa iure commodi velit ea, nemo laborum impedit architecto, praesentium earum unde quae? Velit cumque, quae minima quos mollitia laboriosam placeat eveniet aut molestias. Incidunt reiciendis tempore numquam totam voluptatem eveniet alias ducimus quo nisi ab iusto pariatur mollitia error, voluptatibus velit explicabo delectus distinctio labore quam iure iste quas! Omnis accusamus ex, quidem consequatur rerum dicta enim odit adipisci magni accusantium possimus fuga fugiat, quasi ullam dolor. Explicabo vel quos excepturi dolores amet aperiam, asperiores ad expedita magnam, aliquid accusantium delectus unde soluta, veniam iure dolore nobis aut illo porro labore ipsa quisquam adipisci quod. Alias officia molestias magni quam fugiat facilis quibusdam sequi laboriosam praesentium facere error, commodi sed odio eveniet! Ducimus temporibus tempore ut ipsam!',
  distribiudora: 'Belinda Sánchez Macías - Numero de distribuidora #3584701'

};
